spring:
  application:
    name: trouve ton match
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttm
    username: osselait
    password: postgres
  liquibase:
    driver-class-name: org.postgresql.Driver
    drop-first: false
    enabled: true
    url: jdbc:postgresql://localhost:5432/ttm
    user: osselait
    password: postgres
    change-log: classpath:/db/changelog/db.changelog-master.sql